name: Build & Test
on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - name: Run the script
        run: uptime
