name: Build & Test
on:
  push:
    paths-ignore:
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - env:
           MAIN: ${{ github.ref_name == 'main' }}
           DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
           DISPATCH_MAIN: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'main' }}
        run: |
          echo '
            main=${{ env.MAIN }}
            main=${{ fromJSON(env.MAIN) == true }}
            main=${{ fromJSON(env.MAIN) == false }}
            main=${{ ! env.MAIN }}
            main=${{ ! fromJSON(env.MAIN) }}
          '
      - id: step
        run: |
          echo 'sum=${{
            hashFiles(
              'CHANGELOG.md',
              'Jenkinsfile',
              'README.md'
            )
          }}' >> $GITHUB_OUTPUT
      - run: |
          echo ran
        if: |
          always()
          && false
      - name: Run the script
        run: |
          chmod a+x ./script.sh
          ./script.sh
