name: Build & Test
on:
  push:
    paths-ignore: &ignore-paths
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '**.md'
  pull_request:
    <<: *ignore-paths

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - name: Run the script
        run: uptime
