name: Build & Test
on:
  pull_request:
  push:
    branches:
      - main
      - '!actions/copyright*'
    paths:
      - '**'
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '!README.md'

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: ./script.sh
