name: Build & Test
on:
  push:
    paths-ignore:
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '**/*.md'
  pull_request:

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Run the script
        run: |
          chmod a+x ./script.sh
          ./script.sh
