name: Build & Test
on:
  push: &main-md
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    <<: *main-md

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: ./script.sh
