name: Build & Test
on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    paths-ignore:
      # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
      - '*/**.md'

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: ./script.sh
