name: Build & Test
on:
  push:
  pull_request:
    paths:
      - '!**.md'

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: ./script.sh
